
# This file is automatically generated, you probably don't want to edit this

correlationalOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correlationalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            independents = NULL,
            controls = NULL, ...) {

            super$initialize(
                package='Statkat',
                name='correlational',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..independents <- jmvcore::OptionVariables$new(
                "independents",
                independents)
            private$..controls <- jmvcore::OptionVariables$new(
                "controls",
                controls)

            self$.addOption(private$..dep)
            self$.addOption(private$..independents)
            self$.addOption(private$..controls)
        }),
    active = list(
        dep = function() private$..dep$value,
        independents = function() private$..independents$value,
        controls = function() private$..controls$value),
    private = list(
        ..dep = NA,
        ..independents = NA,
        ..controls = NA)
)

correlationalResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        advice = function() private$.items[["advice"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlational research")
            self$add(jmvcore::Html$new(
                options=options,
                name="advice",
                title="Advice",
                visible="(text)"))}))

correlationalBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correlationalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Statkat',
                name = 'correlational',
                version = c(1,0,0),
                options = options,
                results = correlationalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlational research
#'
#' 
#' @param data .
#' @param dep .
#' @param independents .
#' @param controls .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$advice} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
correlational <- function(
    data,
    dep,
    independents,
    controls) {

    if ( ! requireNamespace('jmvcore'))
        stop('correlational requires jmvcore to be installed (restart may be required)')

    options <- correlationalOptions$new(
        dep = dep,
        independents = independents,
        controls = controls)

    results <- correlationalResults$new(
        options = options)

    analysis <- correlationalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
