
# This file is automatically generated, you probably don't want to edit this

repeatedOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "repeatedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            variables = NULL, ...) {

            super$initialize(
                package='Statkat',
                name='repeated',
                requiresData=TRUE,
                ...)

            private$..variables <- jmvcore::OptionVariables$new(
                "variables",
                variables)

            self$.addOption(private$..variables)
        }),
    active = list(
        variables = function() private$..variables$value),
    private = list(
        ..variables = NA)
)

repeatedResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        advice = function() private$.items[["advice"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Repeated Measurements")
            self$add(jmvcore::Html$new(
                options=options,
                name="advice",
                title="Advice",
                visible="(text)"))}))

repeatedBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "repeatedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Statkat',
                name = 'repeated',
                version = c(1,0,0),
                options = options,
                results = repeatedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Repeated Measurements
#'
#' 
#' @param data .
#' @param variables .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$advice} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
repeated <- function(
    data,
    variables) {

    if ( ! requireNamespace('jmvcore'))
        stop('repeated requires jmvcore to be installed (restart may be required)')

    options <- repeatedOptions$new(
        variables = variables)

    results <- repeatedResults$new(
        options = options)

    analysis <- repeatedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
