
# This file is automatically generated, you probably don't want to edit this

singleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL, ...) {

            super$initialize(
                package='Statkat',
                name='single',
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)

            self$.addOption(private$..var)
        }),
    active = list(
        var = function() private$..var$value),
    private = list(
        ..var = NA)
)

singleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        advice = function() private$.items[["advice"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single variable")
            self$add(jmvcore::Html$new(
                options=options,
                name="advice",
                title="Advice",
                visible="(text)"))}))

singleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Statkat',
                name = 'single',
                version = c(1,0,0),
                options = options,
                results = singleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Single variable
#'
#' 
#' @param data .
#' @param var .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$advice} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
single <- function(
    data,
    var) {

    if ( ! requireNamespace('jmvcore'))
        stop('single requires jmvcore to be installed (restart may be required)')

    options <- singleOptions$new(
        var = var)

    results <- singleResults$new(
        options = options)

    analysis <- singleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
