
# This file is automatically generated, you probably don't want to edit this

singleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL, ...) {

            super$initialize(
                package='Statkat',
                name='single',
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)

            self$.addOption(private$..var)
        }),
    active = list(
        var = function() private$..var$value),
    private = list(
        ..var = NA)
)

singleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        advice = function() private$.items[["advice"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single Variable")
            self$add(jmvcore::Html$new(
                options=options,
                name="advice",
                title="Advice",
                visible="(text)"))}))

singleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "singleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Statkat',
                name = 'single',
                version = c(1,0,0),
                options = options,
                results = singleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Single Variable
#'
#' Statistical method selector for a single variable
#'
#' @examples
#' exampleData <- data.frame(x1 = rnorm(20),
#'                           x2 = as.factor(c(rep(1, 10), rep(2, 10))),
#'                           x3 = as.ordered(rep(1, 10), rep(2, 5), rep(3, 5)))
#'
#' single(exampleData, variable = 'x1')
#' single(exampleData, variable = 'x2')
#' single(exampleData, variable = 'x3')
#'
#' @param data the data as a data frame
#' @param var a string naming a variable from \code{data}
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$advice} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
single <- function(
    data,
    var) {

    if ( ! requireNamespace('jmvcore'))
        stop('single requires jmvcore to be installed (restart may be required)')

    options <- singleOptions$new(
        var = var)

    results <- singleResults$new(
        options = options)

    analysis <- singleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
